### ISSUE TITLE
Post bot-generated message to a specific Fleep room??

### ISSUE THREAD

**Issue by ocean** [anroots/hubot-fleep#13]
Hi there,

Is there a way to make Hubot (via a Hubot script HTTP listener etc) post to a specific Fleep room when using the res.send function??

I can see that the room ID is in the envelope when Hubot is responding to some message from the room, but what about if Hubot creates a message of its own??

Cheers,
Drew

**Comment by anroots** [comment]
Hi there,

I'm not immediately sure - it's been a while since I've worked with this. The following is by memory and might be wrong.

It should definitely be possible for Hubot / Fleep adapter to initiate "post new message" on its own (from external trigger like HTTP listener) - but then it also needs to know where to post this. Room ID could be given by the external trigger or stored in the robot brain (searched by name or something).

Overall, this seems like a Hubot (script) question - perhaps there's more information on it in the official Hubot issue tracker or documentation. There might also be some ready-to-use example scripts.

Let me know if you find the answer or have more hubot-fleep specific questions.

Cheers

**Comment by ocean** [comment]
Thanks, no problems, I'll look through the code for hubot adapters and your Fleep adapter some more.

I thought I'd just ask you the question first in case you knew right away :-)

Cheers.
